### ISSUE TITLE
Should we include app path by default?

### ISSUE THREAD

**Issue by stickeepaul** [stickeeuk/laravel-code-style#13]
The new version of Larastan [removes the `artisan code:analyse` command](https://github.com/nunomaduro/larastan/pull/391) which means you must run `./vendor/bin/phpstan`

This reads the config, so you could either

`./vendor/bin/phpstan analyse app`

or include it in your `phpstan.neon`:

```
parameters:
           paths:
                   - app
...
```

Should this package be updated to include the app path by default?

@stickeerehan

**Comment by stickeerehan** [comment]
Agreed. The current config is out of date, and we should also update the doc.

**Comment by stickeerehan** [comment]
Part of https://github.com/stickeeuk/laravel-code-style/pull/14
