### ISSUE TITLE
Larastan config file contains unnecessary path variable

### ISSUE THREAD

**Issue by stickeepaul** [stickeeuk/laravel-code-style#9]
https://github.com/stickeeuk/laravel-code-style/blob/e7ff4637e78ac4db2f7138941d520ebfe9176050/configs/phpstan.neon#L2

This needed to be `- vendor/nunomaduro/larastan/extension.neon` for me

**Comment by stickeerehan** [comment]
Fixed with https://github.com/stickeeuk/convert/pull/163
